name: Rust

on:
  pull_request:
  push:
    branches: [ "master" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Build test binaries
      run: cargo test --no-run --all-features
    - name: Run tests
      run: cargo test --no-fail-fast --all-features

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Build docs
      run: cargo doc --no-deps --all-features
    - name: Run Clippy lints
      run: cargo clippy
    - name: Check formatting
      run: cargo fmt --check
